version: "3"
services:
  web:
    build:
      context: ../../../..
      dockerfile: res/docker/compose/dokuwiki-dev/Dockerfile
    ports:
     - "8080:80"
    volumes:
     - "../../../../web:/var/www/src/web"
     - "data:/var/www/src/web/dokuwiki/data"
volumes:
  data:
